inherit_from:
  - '.rubocop/default.yml'

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  ExcludedMethods: []
  Exclude:
    - '*.gemspec'

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/rails'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/dummy/**/*'
    - 'spec/dummy/*'
    - 'spec/views/wallaby/resources/*/_xml.html.erb_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'wallaby.gemspec'

Style/WordArray:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/StringLiterals:
  Exclude:
    - 'spec/**/*.rb'
    - 'spec/dummy/config/spring.rb'

Style/SpaceInsideBrackets:
  Exclude:
    - 'spec/**/*.rb'

Style/ExtraSpacing:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/IndentHash:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/SingleLineMethods:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/RedundantSelf:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/RegexpLiteral:
  Exclude:
    - 'spec/helpers/wallaby/application_helper_spec.rb'
    - 'spec/helpers/wallaby/secure_helper_spec.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/**/*_spec.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/adaptors/wallaby/active_record/model_decorator_spec.rb'
