language: ruby
rvm:
  - "2.0.0"
  - "2.1.0"
  - "2.2.0"
env:
  - DB=postgresql
addons:
  postgresql: "9.4"
script:
  - RAILS_ENV=test bundle exec rake --trace db:setup db:migrate spec
before_script:
  - psql -c 'create database wallaby_test' -U postgres
